# Generated by Django 5.0.14 on 2025-04-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_alter_session_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="weight",
        ),
        migrations.AddField(
            model_name="workout",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
            preserve_default=False,
        ),
    ]
