# Generated by Django 5.0.14 on 2025-04-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_rename_weight_workout_working_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="reps",
            field=models.IntegerField(
                choices=[(0, "no change"), (1, "increase"), (2, "decrease")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="sets",
            field=models.IntegerField(
                choices=[(0, "no change"), (1, "increase"), (2, "decrease")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="weight",
            field=models.IntegerField(
                choices=[(0, "no change"), (1, "increase"), (2, "decrease")], default=0
            ),
            preserve_default=False,
        ),
    ]
