# Generated by Django 5.0.14 on 2025-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_workout_reps_workout_sets_workout_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="reps",
            field=models.IntegerField(
                choices=[(0, "no change"), (1, "increase"), (2, "decrease")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="sets",
            field=models.IntegerField(
                choices=[(0, "no change"), (1, "increase"), (2, "decrease")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="weight",
            field=models.IntegerField(
                choices=[(0, "no change"), (1, "increase"), (2, "decrease")], default=0
            ),
        ),
    ]
