# Generated by Django 5.0.14 on 2025-04-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_alter_workout_reps_alter_workout_sets_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="reps",
            new_name="next_reps",
        ),
        migrations.RenameField(
            model_name="workout",
            old_name="sets",
            new_name="next_sets",
        ),
        migrations.RenameField(
            model_name="workout",
            old_name="weight",
            new_name="next_weight",
        ),
    ]
