# Generated by Django 5.0.14 on 2025-06-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0008_rename_reps_workout_next_reps_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="notes",
        ),
    ]
